services:
  pw.admin.web:
    image: pw-admin:local
    container_name: pw_admin_local
    build:
      context: .
      dockerfile: src/Presentation/PW.Admin.Web/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pw.db;Port=5432;Database=${DB_NAME:-PersonelWebsiteDB};Username=${DB_USER:-pw_user};Password=${DB_PASSWORD:-your_strong_password}
      - ConnectionStrings__Redis=pw.redis:6379,password=${REDIS_PASSWORD:-StrongRedisPass123!},abortConnect=false
      - Storage__UseRelativePath=false
      - Storage__Path=/app/uploads
      - Storage__RequestPath=/uploads
    volumes:
      - ./Uploads:/app/uploads
    depends_on:
      pw.db:
        condition: service_healthy
      pw.redis:
        condition: service_healthy
    networks:
      - app-net

  pw.public.web:
    image: pw-public:local
    container_name: pw_public_local
    build:
      context: .
      dockerfile: src/Presentation/PW.Public.Web/Dockerfile
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pw.db;Port=5432;Database=${DB_NAME:-PersonelWebsiteDB};Username=${DB_USER:-pw_user};Password=${DB_PASSWORD:-your_strong_password}
      - ConnectionStrings__Redis=pw.redis:6379,password=${REDIS_PASSWORD:-StrongRedisPass123!},abortConnect=false
      - Storage__UseRelativePath=false
      - Storage__Path=/app/uploads
      - Storage__RequestPath=/uploads
    volumes:
      - ./Uploads:/app/uploads
    depends_on:
      pw.db:
        condition: service_healthy
      pw.redis:
        condition: service_healthy
    networks:
      - app-net

  pw.db:
    image: postgres:16-alpine
    container_name: pw_db_local
    environment:
      POSTGRES_USER: ${DB_USER:-pw_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_strong_password}
      POSTGRES_DB: ${DB_NAME:-PersonelWebsiteDB}
    ports:
      - "5433:5432"
    volumes:
      - db_data_local:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-pw_user} -d ${DB_NAME:-PersonelWebsiteDB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  pw.redis:
    image: redis:alpine
    container_name: pw_redis_local
    ports:
      - "6379:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD:-StrongRedisPass123!}" --save 60 1 --loglevel warning
    volumes:
      - redis_data_local:/data
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${REDIS_PASSWORD:-StrongRedisPass123!}",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db_data_local:
  redis_data_local:
